require("plugins.packer")
require("plugins.filemanager")
require("plugins.telescope.setup")
require("plugins.telescope.mappings")
require("plugins.gitsigns")
require("plugins.blankline")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.statusline")
require("plugins.bufferline")
require("plugins.searchbox")
require("plugins.finecmdline")
require("plugins.notify")

require("plugins.treesitter")
